### ISSUE TITLE
Can't get multiple tag values to work

### ISSUE THREAD

**Issue by MrMMorris** [forward3d/cap-ec2#24]
When specifying multiple tag values for an instance, I can only get tags with single values to work.

These give me "ERROR: Tags should be entered in a key = value pair":
`-T Project=cms,Stages=pre,Roles='web,app,db'`
`-T Project=cms,Stages=pre,Roles=web,app,db`

This results in only the last Roles tag working:
`-T Project=cms,Stages=pre,Roles=web,Roles=app,Roles=db`

I know this might be more of an ec2 question, but I am only using tags in relation to cap-ec2 so I thought I'd ask here.

**Comment by erez-rabih** [comment]
@hbceylan https://github.com/forward3d/cap-ec2/pull/50 supposed to resolve your issues
