### ISSUE TITLE
undefined method `available_roles' for #<Capistrano::Configuration::Servers

### ISSUE THREAD

**Issue by danevron** [forward3d/cap-ec2#34]
Hi,
If you look at the latest Capistrano master [pull request](https://github.com/capistrano/capistrano/commit/6973e5ee3f31fe0f381d891d9ea91f1cdc75b027)
you can see that the available_roles method was removed.

You are calling it in  cap-ec2/lib/cap-ec2/ec2-handler.rb:46

**Comment by andytinycat** [comment]
Released in 0.0.18.
