### ISSUE TITLE
Multiple Roles Not Defining Properly, Migrations not running

### ISSUE THREAD

**Issue by slikstir** [forward3d/cap-ec2#36]
The problem I was having was that the app wasn't running migrations or precompiling assets. So in diving in, here's what I found.

My ec2 server is currently one machine, all roles. 

In my deploy.rb, if i set `bundle_role: :all` and `migration_role: all`, it works.

In my staging.rb, I have the following

> ec2_role :app, user: :ubuntu
> ec2_role :web, user: :ubuntu
> ec2_role :cron, user: :ubuntu
> ec2_role :db, user: :ubuntu

I additionally found that if I put  `ec2_role: db, user: ubuntu` as the first line of my production.rb, it works. When it was working, I outputted the results of `fetch(:migration_role)` and found the following 

`[#<Capistrano::Configuration::Server:0x00000105b75dd0 @user=:ubuntu, @hostname="ec2-54-221-198-113.compute-1.amazonaws.com", @port=nil, @properties=#<Capistrano::Configuration::Server::Properties:0x00000105b75808 @properties={:aws_instance_id=>"i-ce3a3225"}, @roles=#<Set: {:db}>>, @ssh_options={}, @netssh_options={:user=>:ubuntu, :forward_agent=>true}>]`

What it looks like to me, is that the only role that's being defined is the first role. 

Additionally, I need to rewrite the migration task from capistrano/rake to not use the "primary" server, which doesn't appear to work regardless of how I tag an ec2_role with primary: true. https://github.com/capistrano/rails/blob/master/lib/capistrano/tasks/migrations.rake

Am I missing something? Or are these bugs?

**Comment by ejhayes** [comment]
Aha...I wasn't able to find any major faults with this gem...never thought to try out different versions of capistrano.  Thanks for posting your solution @chopmo!

**Comment by slikstir** [comment]
Thanks @chopmo. I'll chime back in when we get to implementing this.

**Comment by andytinycat** [comment]
I believe this is fixed in upstream now.
