### ISSUE TITLE
`colored` gem is old and broken, maybe use `colorize`?

### ISSUE THREAD

**Issue by Tomtomgo** [forward3d/cap-ec2#39]
After running `bundle update` I get an issue with the `colored` gem:

```bash
SSHKit::Runner::ExecuteError: Exception while executing as moi@ec2-magicnumber.us-west-2.compute.amazonaws.com: no implicit conversion of Hash into String
/usr/local/rvm/gems/ruby-2.1.2@moi/gems/colored-1.2/lib/colored.rb:70:in `colorize'
/usr/local/rvm/gems/ruby-2.1.2@moi/gems/sshkit-1.6.1/lib/sshkit/color.rb:7:in `black'
```

It seems `colored` and `colorized` do kinda the same thing and now seem to be clashing.
The [`colored`](https://github.com/defunkt/colored) gem hasn't been updated in 5 years and doesn't allow issues to be made on the Github repo. Using [`colorize`](https://github.com/fazibear/colorize) should be better, they do update regularly and do allow issues to be reported.

**Comment by Tomtomgo** [comment]
I can confirm that `colored` and the latest (0.7.5) version of `colorize` are clashing, I reverted to using `colorized` 0.7.4 and boom, everything works again!

Still, might be good to change to the gem that doesn't break.

**Comment by Bladrak** [comment]
I do reproduce this (thanks @Tomtomgo for the version to downgrade to). I second your thought on changing to ``colorize`` gem.

**Comment by andytinycat** [comment]
I agree; I think the choice to use `colored` was a bad move when I originally wrote the gem.

If you've got time, a PR would be welcomed. If not, I'll get to it next week as I lack the bandwidth to do this now.
