### ISSUE TITLE
cap-ec2 not running other cap tasks

### ISSUE THREAD

**Issue by obenziane2** [forward3d/cap-ec2#46]
I was successfully be able run deploy against ec2 instances, however it does not run other tasks defined for that role,  I'm running "Capistrano Version: 3.3.5 " and also tried "Capistrano Version: 3.2.1 " gave  me the same results.  Any idea on how fix this ?

Thanks

**Comment by andytinycat** [comment]
What version of Cap-EC2 are you running? What do you mean by "it does not run other tasks" - do you mean during the deploy, or running `cap production [task]`? Can you give me an example of a task that fails?

**Comment by zecharyah** [comment]
@andytinycat Hey, I have the same issue. When I run cap staging ec2:status the table appears empty, what can be the issue ?

**Comment by dlahn** [comment]
Not able to reproduce this. If this is still an issue, please re-open with some additional info.
