### ISSUE TITLE
How to disable "Stages"?

### ISSUE THREAD

**Issue by issei-m** [forward3d/cap-ec2#52]
This gem is great idea! But I'm not separating stages in my projects. It means only "production" stage is there.

So the "Stage" concept is not necessary for me now. But it seems not to be disabled. (Following code I tried could not find any instances if none is set "Stage" tag.):

``` ruby
set :ec2_stages_tag, nil
```

Can I disable "Stage"?

**Comment by kylev** [comment]
You really can't. Stages are fundamental to capistrano3. That you only have a single stage is incidental.
