### ISSUE TITLE
Does not work for instances with same private ip addresses located in different VPCs.

### ISSUE THREAD

**Issue by sebastienliu** [forward3d/cap-ec2#57]
I have application nodes with same ip addresses on Production and Staging but they are located in different VPCs. When I launch ec2:status, on staging is working fine, but on production environment, SSHKit always complains about fingerprint does not match for private ip addresses.

SSHKit::Runner::ExecuteError: Exception while executing on host 172.31.10.10: fingerprint does not match for "172.31.10.10"

Net::SSH::HostKeyMismatch: fingerprint does not match for "172.31.10.10"

**Comment by theist** [comment]
Seems that isn't an issue of cap-ec2. Capistrano uses SSHKit gem which relies in your ssh-client  config for accessing nodes by ssh. You must tell shh not to store fingerprints (or not to stop ssh when fingerprints does not match) on those servers using your .ssh/config

**Comment by sebastienliu** [comment]
@theist You are correct. It's been fixed.
