### ISSUE TITLE
add latest version to RubyGems

### ISSUE THREAD

**Issue by AlexMorreale** [forward3d/cap-ec2#69]
Any chance release 1.1.0 will be on rubygems soon?

https://github.com/forward3d/cap-ec2/commit/7ef7287aeb722ca44a55d10fc88a04af134fc3e7

**Comment by lehresman** [comment]
Yeah, we just got bit by this too.  For now we're pointing to the commit in our Gemfile.

**Comment by tlrdstd** [comment]
This is keeping me from upgrading to Ruby 2.4.1. `aws-sdk-v1` requires `json` version 1.8, which is not compatible with Ruby 2.4. I can't remove the `aws-sdk-v1` dependency until `cap-ec2` 1.1.0 is released.

**Comment by dlahn** [comment]
Hi,

We are working on getting this on to RubyGems as soon as possible. 

Best regards,
Dave

**Comment by AlexMorreale** [comment]
![hulk_ship_it](https://user-images.githubusercontent.com/8332983/29425258-a11eae5c-8350-11e7-97ca-8e1207aa8e10.jpeg)

**Comment by tlrdstd** [comment]
Any ETA on this?

**Comment by okuramasafumi** [comment]
@tlrdstd I successfully upgrade my Ruby to `2.4.1`. New `json` gem has been released so upgrading `cap-ec2` to `1.0.0` and updating `json` gem will work.
Anyway I'm waiting for the new release of this gem uploaded to `rubygems.org`, @dlahn

**Comment by magnusvk** [comment]
It's been eight months... Will we ever see a RubyGems release? 😄

**Comment by dlahn** [comment]
We have re-gained access to the gem, and have now pushed v1.1.1 to RubyGems. Apologies for the delay.
